export const loadingMessages = [
  "Infusing garlic-infused oil...", "Simmering the low FODMAP broth...", "Preheating the oven...",
  "Sprinkling fresh herbs...", "Tasting the soup...", "Plating your meals...",
  "Washing the spinach...", "Marinating the firm tofu...", "Slicing the red peppers...",
  "Dicing the carrots...", "Boiling the basmati rice...", "Roasting the potatoes...",
  "Grilling the fresh salmon...", "Flipping gluten-free pancakes...", "Whisking the eggs...",
  "Kneading gluten-free dough...", "Baking the sourdough...", "Melting the butter...",
  "Sautéing spring onion greens...", "Zesting the lemon...", "Squeezing the limes...",
  "Peeling the fresh ginger...", "Crushing the walnuts...", "Toasting the pumpkin seeds...",
  "Blending a berry smoothie...", "Brewing peppermint tea...", "Steaming the bok choy...",
  "Stir-frying the rice noodles...", "Seasoning the steak...", "Garnishing with parsley...",
  "Caramelizing the sugar...", "Whipping lactose-free cream...", "Folding the batter...",
  "Measuring the rice flour...", "Pouring the olive oil...", "Grating the cheddar...",
  "Sifting the cocoa...", "Slicing the cucumber...", "Tossing the rocket salad...",
  "Glazing the salmon...", "Poaching the rhubarb...", "Braising the beef...",
  "Curing the meat...", "Fermenting the sourdough...", "Pickling the cucumbers...",
  "Smoking the fish...", "Slow-cooking the stew...", "Air-frying the chips...",
  "Cooling the pie...", "Setting the table...", "Folding the napkins...",
  "Polishing the glasses...", "Lighting the candles...", "Arranging the flowers...",
  "Chopping the chives...", "Mashing the potatoes...", "Whisking the vinaigrette...",
  "Deglazing the pan...", "Reducing the balsamic...", "Blanching the green beans...",
  "Searing the scallops...", "Poaching the eggs...", "Toasting the gluten-free bread...",
  "Spreading the peanut butter...", "Drizzling the maple syrup...", "Cracking the black pepper...",
  "Grinding the sea salt...", "Peeling the kiwi...", "Slicing the strawberries...",
  "Hullng the strawberries...", "Pitting the olives...", "Shucking the oysters...",
  "Cleaning the mussels...", "Deveining the prawns...", "Scaling the fish...",
  "Filleting the trout...", "Deboning the chicken...", "Trussing the turkey...",
  "Basting the roast...", "Skimming the fat...", "Straining the stock...",
  "Clarifying the butter...", "Tempering the chocolate...", "Folding in the blueberries...",
  "Dusting with icing sugar...", "Piping the frosting...", "Glazing the donuts...",
  "Proofing the yeast...", "Scoring the loaf...", "Steaming the mussels...",
  "Sautéing the oyster mushrooms...", "Grilling the zucchini...", "Roasting the parsnips...",
  "Boiling the quinoa...", "Fluffing the couscous...", "Rinsing the lentils...",
  "Soaking the chia seeds...", "Toasting the pine nuts...", "Roasting the macadamias...",
  "Slicing the radishes...", "Grating the ginger...", "Zesting the orange...",
  "Juicing the grapefruit...", "Infusing the rosemary...", "Steeping the chamomile...",
  "Frothing the lactose-free milk...", "Layering the lasagna...", "Stuffing the peppers...",
  "Rolling the sushi...", "Wrapping the spring rolls...", "Shaping the meatballs...",
  "Skewering the kebabs...", "Brushing with egg wash...", "Sprinkling the sesame seeds...",
  "Garnishing with cilantro...", "Drizzling the sesame oil...", "Whisking the miso...",
  "Simmering the laksa...", "Stirring the risotto...", "Ladling the soup...",
  "Shaving the parmesan...", "Crumbling the feta...", "Slicing the mozzarella...",
  "Toasting the pecans...", "Chopping the peanuts...", "Blending the pesto...",
  "Whisking the hollandaise...", "Simmering the marinara...", "Reducing the red wine...",
  "Sautéing the kale..."
];

export const generationHeaders = [
  "Cooking up the rest of your week...",
  "Simmering your weekly plan...",
  "Plating your 7-day menu...",
  "Whisking together your meals...",
  "Preparing your grocery list...",
  "Garnishing your week ahead...",
  "Sautéing your food schedule...",
  "Baking your budget-friendly plan..."
];
